// src/scripts/seedDatabase.ts

import { collection, doc, setDoc, getDocs, deleteDoc } from 'firebase/firestore';
import { db } from '../firebase/config';
import { Microgame } from '../types';
import { microgames as microgameComponents } from '../microgames';

// This map contains the detailed, correct metadata for each game.
// The KEY must EXACTLY match the PascalCase filename of the component.
const microgameData: { [key: string]: Omit<Microgame, 'id' | 'name' | 'skins' | 'isFavorite' | 'isActive'> } = {
  Avoid: { baseType: 'Player Movement', mechanicType: 'skill', controls: 'WASD or Arrows for movement', length: 5, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Bargain Hunter', 'Indecisive Shopper'], trackableEvents: [ { eventId: 'win', label: 'Win Game', defaultPoints: 100 }, { eventId: 'lose', label: 'Lose Game', defaultPoints: 0 } ], },
  Build: { baseType: 'Jigsaw Puzzle', mechanicType: 'skill', controls: 'Click and Drag', length: 7, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter', 'Indecisive Shopper'] },
  Catch: { baseType: 'Catch Falling Objects', mechanicType: 'skill', controls: 'A and D or Left and Right Arrows', length: 5, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  Claw: { baseType: 'Claw Machine', mechanicType: 'skill', controls: 'A and D or Left and Right Arrows and Spacebar or Click', length: 10, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  Clean: { baseType: 'Wipe to Reveal', mechanicType: 'skill', controls: 'Click and Drag', length: 5, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Bargain Hunter', 'Indecisive Shopper'] },
  Collect: { baseType: 'Collection', mechanicType: 'skill', controls: 'Point and Click', length: 5, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Bargain Hunter', 'Indecisive Shopper'] },
  Consume: { baseType: 'Rapid Clicking', mechanicType: 'skill', controls: 'Point and Click', length: 5, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Bargain Hunter', 'Indecisive Shopper'] },
  Drop: { baseType: 'Timing Drop', mechanicType: 'skill', controls: 'Click or Spacebar', length: 7, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  Escape: { baseType: 'Maze Navigation', mechanicType: 'skill', controls: 'WASD or Arrows for movement', length: 5, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Bargain Hunter', 'Indecisive Shopper'] },
  Frame: { baseType: 'Positioning', mechanicType: 'skill', controls: 'Click and Drag', length: 5, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  Grab: { baseType: 'Reaction / Tapping', mechanicType: 'skill', controls: 'Click or Spacebar', length: 7, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  Grow: { baseType: 'Collection / Growth', mechanicType: 'skill', controls: 'Click, Drag, and Drop', length: 7, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter'] },
  Like: { baseType: 'Reaction / Identification', mechanicType: 'skill', controls: 'Point and Click', length: 7, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  LineUp: { baseType: 'Sequencing / Ordering', mechanicType: 'skill', controls: 'Click, Drag, and Drop', length: 7, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter'] },
  Match: { baseType: 'Memory / Card Flip', mechanicType: 'skill', controls: 'Point and Click', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter'] },
  MatchUp: { baseType: 'Matching Pairs', mechanicType: 'skill', controls: 'Point and Click', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter'] },
  Organize: { baseType: 'Categorization', mechanicType: 'skill', controls: 'Click, Drag, and Drop', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter'] },
  Package: { baseType: 'Drag and Drop', mechanicType: 'skill', controls: 'Click, Drag, and Drop', length: 7, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Bargain Hunter'] },
  Pop: { baseType: 'Reaction / Tapping', mechanicType: 'skill', controls: 'Point and Click', length: 7, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  Spot: { baseType: 'Reaction / Identification', mechanicType: 'skill', controls: 'Point and Click', length: 7, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter'] },
  Trade: { baseType: 'Selection', mechanicType: 'skill', controls: 'Point and Click', length: 7, tempo: 'Normal', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Bargain Hunter', 'Indecisive Shopper'] },
  Vote: { baseType: 'Selection', mechanicType: 'skill', controls: 'Point and Click', length: 7, tempo: 'Fast', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['Impulse Shopper', 'Indecisive Shopper'] },
  CupAndBall: { baseType: 'Shell Game', mechanicType: 'chance', controls: 'Click to Choose', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['All'] },
  DiceRoll: { baseType: 'Dice Roll', mechanicType: 'chance', controls: 'Click to Roll', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['All'] },
  PickAGift: { baseType: 'Mystery Box', mechanicType: 'chance', controls: 'Click to Open', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['All'] },
  ScratchCard: { baseType: 'Scratch-Off', mechanicType: 'chance', controls: 'Click and Drag', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['All'] },
  SpinTheWheel: { baseType: 'Prize Wheel', mechanicType: 'chance', controls: 'Click to Spin', length: 10, tempo: 'Slow', gameplayExperience: 'Generalized', compatibleConversionGoals: ['Increase Overall Conversion Rate', 'Promote Specific Products or Collections', 'Increase Average Order Value (AOV)', 'Promote a Site-Wide Sale or Offer', 'Generate Leads', 'Collect Email or SMS Subscribers', 'Increase Account or Loyalty Program Sign-ups', 'Drive Social Media Engagement'], compatibleProductCategories: ['All'], compatibleCustomerTypes: ['All'] },
};

export async function seedMicrogames() {
    const microgamesCollection = collection(db, 'microgames');
    
    console.log("Clearing existing microgames...");
    const existingDocs = await getDocs(microgamesCollection);
    for (const docSnapshot of existingDocs.docs) {
        await deleteDoc(doc(db, 'microgames', docSnapshot.id));
    }
    console.log("Existing microgames cleared.");

    console.log("Seeding new master list of microgames from file system...");
    
    // Get the list of games directly from our automated index file
    const gameIds = Object.keys(microgameComponents);

    for (const gameId of gameIds) {
        const metadata = microgameData[gameId];
        if (!metadata) {
            console.warn(`Warning: No metadata found for game component "${gameId}". Skipping.`);
            continue;
        }

        // The document ID in Firestore is now the PascalCase filename
        const docRef = doc(microgamesCollection, gameId);
        
        // A simple function to create a display name from PascalCase, e.g., "DiceRoll" -> "Dice Roll"
        const createDisplayName = (pascalCase: string) => pascalCase.replace(/([A-Z])/g, ' $1').trim();

        const fullGameData: Omit<Microgame, 'id'> = {
            name: createDisplayName(gameId),
            ...metadata,
            isActive: true,
            skins: {},
            isFavorite: false
        };
        
        try {
            await setDoc(docRef, fullGameData);
            console.log(`Successfully seeded: ${gameId}`);
        } catch (error) {
            console.error(`Error seeding ${gameId}:`, error);
        }
    }
    console.log("Database master list seeding complete!");
}