/* src/constants/defaultMacrogameState.ts */

import { Macrogame } from '../types';

export const DEFAULT_MACROGAME_STATE: Omit<Macrogame, 'id' | 'type'> & { id: string | null } = {
    id: null,
    name: '',
    conversionGoal: '',
    gameplayExperience: '',
    sectors: [],
    categories: [],
    subcategories: [],
    seasonality: [],
    targetAudience: [],
    promotionCompatibility: [],
    createdAt: new Date().toISOString(),
    globalStyling: {
        theme: 'dark',
        fontType: 'standard',
        fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
        googleFontUrl: '',
        customFontUrl: '',
        borderRadius: 6,
        width: 60,
        height: 95,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 0,
        paddingRight: 0,
        hudLayout: 'viewport',
        hudPaddingY: 12,
        hudPaddingX: 18,
    },
    config: {
        backgroundMusicUrl: null,
        screenFlowType: 'Overlay',
        showLineItemDetails: true,
        progressFormat: 'visual',
        progressShowLabels: false,
        progressStyle: {
            inactiveColor: 'rgba(255, 255, 255, 0.25)',
            activeColor: '#00d2d3',
            rewardColor: '#f1c40f',
            activeTextColor: '#ffffff',
            inactiveTextColor: 'rgba(255, 255, 255, 0.6)',
        },
        lightProgressStyle: {
            inactiveColor: 'rgba(0, 0, 0, 0.15)',
            activeColor: '#0866ff',
            rewardColor: '#f1c40f',
            activeTextColor: '#333333',
            inactiveTextColor: 'rgba(0, 0, 0, 0.6)',
        },
        preGameConfig: {
            headline: '<h1 style="text-align: center; text-transform: uppercase;">{{game_title}}</h1>',
            bodyText: '<p style="text-align: center; font-size: 1.25rem;">{{game_controls}}</p>',
            textSpacing: 12,
            blockSpacing: 24,
            transition: {
                type: 'auto',
                autoDuration: 3,
                showCountdown: true,
                countdownText: 'Continuing in {{time}}',
                interactionMethod: 'click',
                clickFormat: 'button',
                disclaimerText: 'Click anywhere to start',
                pulseAnimation: true,
                buttonConfig: {
                    text: 'Start',
                    borderRadius: 6,
                    paddingVertical: 12,
                    paddingHorizontal: 32,
                    widthMode: 'max',
                    customWidth: 50,
                    strokeStyle: 'none',
                    strokeWidth: 2,
                },
                buttonStyle: { backgroundColor: '#0866ff', textColor: '#ffffff', strokeColor: '#0866ff' },
                lightButtonStyle: { backgroundColor: '#0866ff', textColor: '#ffffff', strokeColor: '#0866ff' },
            }
        },
        resultConfig: {
            enabled: true,
            format: 'overlay',
            winText: '<h1 style="text-align: center; color: #2ecc71; text-transform: uppercase;">WIN!</h1>',
            winBodyText: '<p style="text-align: center; font-size: 1.25rem;">Congrats, you won! Click to continue to the next stage.</p>',
            lossText: '<h1 style="text-align: center; color: #e74c3c; text-transform: uppercase;">GAME OVER</h1>',
            lossBodyText: '<p style="text-align: center; font-size: 1.25rem;">Oh no, you lost!</p>',
            tryAgainText: '<h1 style="text-align: center; color: #f1c40f; text-transform: uppercase;">TRY AGAIN</h1>',
            tryAgainBodyText: '<p style="text-align: center; font-size: 1.25rem;">You didn\'t reach the goal, but don\'t worry. You can try again!</p>',
            textSpacing: 12,
            buttonSpacing: 12,
            blockSpacing: 24,
            showPlayAgainOnWin: false,
            showPlayAgainOnLoss: true,
            showPlayAgainOnTryAgain: true,
            transition: {
                type: 'interact',
                interactionMethod: 'click',
                clickFormat: 'button',
                disclaimerText: 'Click anywhere to continue',
                pulseAnimation: true,
                buttonConfig: {
                    text: 'Continue',
                    borderRadius: 6,
                    paddingVertical: 12,
                    paddingHorizontal: 32,
                    widthMode: 'max',
                    customWidth: 50,
                    strokeStyle: 'none',
                    strokeWidth: 2,
                },
                buttonStyle: { backgroundColor: '#ffffff', textColor: '#333333', strokeColor: '#ffffff' },
                lightButtonStyle: { backgroundColor: '#333333', textColor: '#ffffff', strokeColor: '#333333' },
            },
            secondaryButtonConfig: {
                text: 'Play Again',
                borderRadius: 6,
                paddingVertical: 12,
                paddingHorizontal: 32,
                widthMode: 'max',
                customWidth: 50,
                strokeStyle: 'solid',
                strokeWidth: 2,
            },
            secondaryButtonStyle: { backgroundColor: 'transparent', textColor: '#ffffff', strokeColor: '#ffffff' },
            lightSecondaryButtonStyle: { backgroundColor: 'transparent', textColor: '#333333', strokeColor: '#333333' },
        }
    },
    introScreen: {
        enabled: true,
        headline: '<h1 style="text-align: center;">GET READY!</h1>',
        bodyText: '<p style="text-align: center; font-size: 1.25rem;">Play a 10 second minigame for a chance to win a special reward!</p>',
        textShadowEnabled: false,
        transition: {
            type: 'interact',
            interactionMethod: 'click',
            clickFormat: 'button',
            disclaimerText: 'Click anywhere to continue',
            pulseAnimation: true,
            autoDuration: 3,
            showCountdown: true,
            countdownText: 'Continuing in {{time}}',
            buttonConfig: {
                text: 'Start',
                borderRadius: 6,
                paddingVertical: 12,
                paddingHorizontal: 32,
                widthMode: 'max',
                customWidth: 50,
                strokeStyle: 'none',
                strokeWidth: 2,
                enableHoverAnimation: true
            },
            buttonStyle: { backgroundColor: '#0866ff', textColor: '#ffffff', strokeColor: '#0866ff' },
            lightButtonStyle: { backgroundColor: '#0866ff', textColor: '#ffffff', strokeColor: '#0866ff' }
        },
        backgroundImageUrl: null,
        spotlightImageUrl: null,
        spotlightImageLayout: null,
        style: {
            verticalAlign: 'center',
            spacing: 12,
            blockSpacing: 24,
            textPaddingTop: 0,
            textPaddingBottom: 0,
            textPaddingLeft: 0,
            textPaddingRight: 0,
            contentGap: 24,
            spotlightSize: 40,
            spotlightScale: 100,
            spotlightAlignX: 'center',
            spotlightAlignY: 'center',
            spotlightFit: 'cover',
            spotlightBorderRadius: 6,
            spotlightPaddingTop: 0,
            spotlightPaddingBottom: 0,
            spotlightPaddingLeft: 0,
            spotlightPaddingRight: 0,
        },
        lightStyle: {}
    },
    promoScreen: {
        enabled: false,
        headline: '<h1 style="text-align: center;">Special Promotion!</h1>',
        bodyText: '<p style="text-align: center; font-size: 1.25rem;">Check out this special offer just for you. Submit the required information on the next screen to get your reward!</p>',
        textShadowEnabled: false,
        transition: {
            type: 'interact',
            interactionMethod: 'click',
            clickFormat: 'button',
            disclaimerText: 'Click anywhere to continue',
            pulseAnimation: true,
            autoDuration: 5,
            showCountdown: true,
            countdownText: 'Continuing in {{time}}',
            buttonConfig: {
                text: 'Continue',
                borderRadius: 6,
                paddingVertical: 12,
                paddingHorizontal: 32,
                widthMode: 'max',
                customWidth: 50,
                strokeStyle: 'none',
                strokeWidth: 2,
                enableHoverAnimation: true
            },
            buttonStyle: { backgroundColor: '#0866ff', textColor: '#ffffff', strokeColor: '#0866ff' },
            lightButtonStyle: { backgroundColor: '#0866ff', textColor: '#ffffff', strokeColor: '#0866ff' }
        },
        backgroundImageUrl: null,
        spotlightImageUrl: null,
        spotlightImageLayout: null,
        style: {
            verticalAlign: 'center',
            spacing: 12,
            blockSpacing: 24,
            textPaddingTop: 0,
            textPaddingBottom: 0,
            textPaddingLeft: 0,
            textPaddingRight: 0,
            contentGap: 24,
            spotlightSize: 40,
            spotlightScale: 100,
            spotlightAlignX: 'center',
            spotlightAlignY: 'center',
            spotlightFit: 'cover',
            spotlightBorderRadius: 6,
            spotlightPaddingTop: 0,
            spotlightPaddingBottom: 0,
            spotlightPaddingLeft: 0,
            spotlightPaddingRight: 0,
        },
        lightStyle: {}
    },
    flow: [],
    conversionScreenId: null,
    audioConfig: {}, 
};