// src/App.styles.ts
import React from 'react';

export const styles: {[key: string]: React.CSSProperties} = {
  page: { fontFamily: 'system-ui, sans-serif', backgroundColor: '#f0f2f5', minHeight: '100vh', color: '#1c1e21' },
  header: { backgroundColor: '#ffffff', padding: '1rem 2rem', borderBottom: '1px solid #ddd', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  nav: { display: 'flex', gap: '1rem' },
  navButton: { background: 'none', border: 'none', padding: '0.5rem 1rem', fontSize: '1rem', cursor: 'pointer', color: '#606770', borderBottom: '2px solid transparent' },
  navButtonActive: { color: '#0866ff', borderBottom: '2px solid #0866ff', fontWeight: 'bold' },
  main: { width: '100%', maxWidth: '1400px', margin: '2rem auto', padding: '0 2rem', boxSizing: 'border-box' },
  creatorSection: { backgroundColor: '#ffffff', padding: '2rem', borderRadius: '8px', marginBottom: '2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' },
  h2: { color: '#1c1e21', fontSize: '1.75rem', marginBottom: '1.5rem' },
  h3: { color: '#606770', fontSize: '1.25rem', marginTop: '2rem', borderBottom: '1px solid #ddd', paddingBottom: '0.5rem', marginBottom: '1.5rem' },
  h4: { color: '#1c1e21', fontSize: '1.1rem', marginTop: '1rem', marginBottom: '0.5rem' },
  descriptionText: { marginTop: '-1rem', marginBottom: '1.5rem', color: '#606770' },
  formRow: { display: 'flex', gap: '1rem', marginBottom: '1rem' },
  formHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  input: { padding: '0.75rem', borderWidth: '1px', borderStyle: 'solid', borderColor: '#ccc', borderRadius: '6px', fontSize: '1rem', width: '100%', boxSizing: 'border-box', backgroundColor: '#ffffff', color: '#1c1e21' },
  cardContainer: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '1rem', alignItems: 'start' },
  card: { backgroundColor: '#f7f7f7', padding: '1rem', borderRadius: '8px', border: '2px solid transparent', cursor: 'default', transition: 'all 0.2s', color: '#333' },
  cardSelected: { borderColor: '#0866ff', backgroundColor: '#eaf5fc' },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontWeight: 'bold' },
  cardDetails: { marginTop: '1rem', fontSize: '0.9rem', borderTop: '1px solid #eee', paddingTop: '0.5rem' },
  accordionButton: { fontSize: '1rem', background: 'none', border: 'none', cursor: 'pointer', color: '#606770' },
  addButton: { backgroundColor: '#2ecc71', color: 'white', border: 'none', padding: '0.75rem 1.5rem', borderRadius: '6px', fontSize: '1rem', cursor: 'pointer', marginTop: '1rem' },
  saveButton: { backgroundColor: '#0866ff', color: 'white', border: 'none', padding: '0.75rem 1.5rem', borderRadius: '6px', fontSize: '1rem', cursor: 'pointer' },
  secondaryButton: { backgroundColor: '#6c757d', color: 'white', border: 'none', padding: '0.75rem 1.5rem', borderRadius: '6px', fontSize: '1rem', cursor: 'pointer' },
  publishButton: { backgroundColor: '#0866ff', color: 'white', border: 'none', padding: '0.5rem 1rem', borderRadius: '6px', fontSize: '0.9rem', cursor: 'pointer' },
  previewButton: { backgroundColor: '#17a2b8', color: 'white', border: 'none', padding: '0.5rem 1rem', borderRadius: '6px', fontSize: '0.9rem', cursor: 'pointer' },
  editButton: { backgroundColor: '#f0f2f5', color: '#606770', border: '1px solid #ccc', padding: '0.5rem 1rem', borderRadius: '6px', fontSize: '0.9rem', cursor: 'pointer' },
  deleteButton: { backgroundColor: '#fa383e', color: 'white', border: 'none', padding: '0.5rem 1rem', borderRadius: '6px', fontSize: '0.9rem', cursor: 'pointer' },
  flowContainer: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '1rem', padding: '1rem', backgroundColor: '#e4e6eb', borderRadius: '8px' },
  flowCard: { position: 'relative', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', width: '200px', height: '110px', padding: '0.5rem', paddingTop: '1.5rem', backgroundColor: 'white', boxShadow: '0 4px 6px rgba(0,0,0,0.1)', border: '1px solid #ddd', borderRadius: '8px', boxSizing: 'border-box' },
  flowCardRemoveButton: { position: 'absolute', top: '2px', right: '5px', background: 'none', border: 'none', fontSize: '1.5rem', color: '#999', cursor: 'pointer', padding: '0' },
  staticFlowCard: { fontWeight: 'bold', color: '#606770', borderStyle: 'dashed' },
  flowCardStep: { position: 'absolute', top: '5px', left: '8px', backgroundColor: '#606770', color: 'white', borderRadius: '50%', width: '20px', height: '20px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.8rem', fontWeight: 'bold' },
  flowCardStepAdd: {
    width: '50px',
    borderRadius: '3px'
  },
  flowCardActions: { position: 'absolute', bottom: '5px', right: '5px', display: 'flex' },
  flowCardButton: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '1rem', color: '#606770', padding: '0.2rem' },
  flowCardArchived: { borderColor: '#e74c3c', backgroundColor: '#fff2f2' },
  archivedText: { color: '#e74c3c', fontWeight: 'bold', fontSize: '0.8rem', marginTop: '0.25rem'},
  flowArrow: { fontSize: '1.5rem', color: '#606770', fontWeight: 'bold' },
  configContainer: { display: 'flex', flexDirection: 'column', gap: '1rem', marginTop: '1rem' },
  configRow: { display: 'flex', gap: '1.5rem', alignItems: 'flex-end' },
  configItem: { display: 'flex', flexDirection: 'column', gap: '0.5rem', flex: 1 },
  createButton: { backgroundColor: '#0866ff', color: 'white', border: 'none', padding: '1rem 2rem', borderRadius: '6px', fontSize: '1.1rem', cursor: 'pointer', marginTop: '2rem', marginBottom: '2rem', fontWeight: 'bold' },
  listItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'white', padding: '1rem', borderRadius: '6px', marginBottom: '1rem', boxShadow: '0 1px 2px rgba(0,0,0,0.05)' },
  listItemRight: { display: 'flex', alignItems: 'center', gap: '1rem' },
  tag: { backgroundColor: '#e4e6eb', color: '#606770', padding: '0.2rem 0.6rem', borderRadius: '10px', fontSize: '0.8rem' },
  warningTag: { backgroundColor: '#f39c12', color: 'white', padding: '0.2rem 0.6rem', borderRadius: '10px', fontSize: '0.8rem', fontWeight: 'bold', marginLeft: '1rem' },
  inputAlert: { borderColor: '#fd7e14', boxShadow: '0 0 0 2px rgba(253, 126, 20, 0.3)' },
  managerHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' },
  managerList: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  managerActions: { display: 'flex', alignItems: 'center', gap: '1rem' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.6)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
  modalContent: { backgroundColor: 'white', padding: '0', borderRadius: '8px', width: '90%', maxWidth: '600px', boxShadow: '0 5px 15px rgba(0,0,0,0.3)', maxHeight: '90vh', display: 'flex', flexDirection: 'column' },
  modalContentMedium: { backgroundColor: 'white', padding: '0', borderRadius: '8px', width: '90%', maxWidth: '800px', boxShadow: '0 5px 15px rgba(0,0,0,0.3)', maxHeight: '90vh', display: 'flex', flexDirection: 'column' },
  modalBody: { padding: '2rem', overflowY: 'auto', flexGrow: 1 },
  modalContentLarge: { backgroundColor: 'white', borderRadius: '8px', width: '90%', maxWidth: '1200px', boxShadow: '0 5px 15px rgba(0,0,0,0.3)', maxHeight: '90vh', display: 'flex', flexDirection: 'column' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #eee', padding: '1.5rem 2rem', flexShrink: 0 },
  modalCloseButton: { background: 'none', border: 'none', fontSize: '1.5rem', cursor: 'pointer' },
  rewardsList: { listStyle: 'none', padding: 0, margin: 0, maxHeight: '200px', overflowY: 'auto' },
  rewardItem: { display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.75rem 0.5rem', borderBottom: '1px solid #f0f0f0' },
  pointsInput: { width: '80px', padding: '0.5rem', marginLeft: 'auto' },
  modalFooter: { display: 'flex', justifyContent: 'flex-end', gap: '1rem', paddingTop: '1rem', marginTop: 'auto', borderTop: '1px solid #eee', padding: '1.5rem 2rem', flexShrink: 0 },
  rewardsListContainer: {},
  rewardsCreateForm: { display: 'flex', flexDirection: 'column', gap: '1rem', paddingTop: '1rem' },
  rewardsListFull: { listStyle: 'none', padding: 0, margin: 0 },
  rewardListItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#f7f7f7', padding: '1rem', borderRadius: '6px', marginBottom: '0.5rem' },
  rewardInfo: { display: 'flex', flexDirection: 'column', gap: '0.5rem' },
  rewardAnalytics: { display: 'flex', gap: '1rem', fontSize: '0.8rem', color: '#606770' },
  rewardActions: { display: 'flex', gap: '0.5rem' },
  statusActive: { color: '#28a745', fontWeight: 'bold' },
  statusDraft: { color: '#6c757d', fontWeight: 'bold' },
  paginationContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '1rem', marginTop: '1.5rem' },
  paginationButton: { backgroundColor: '#f0f2f5', color: '#606770', border: '1px solid #ccc', padding: '0.5rem 1rem', borderRadius: '6px', fontSize: '0.9rem', cursor: 'pointer' },
  paginationText: { fontSize: '0.9rem', color: '#606770' },
  configSection: { borderTop: '1px solid #ddd', marginTop: '1.5rem', paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' },
  scheduleContainer: { display: 'flex', flexDirection: 'column', gap: '0.75rem', padding: '0.75rem', border: '1px solid #ccc', borderRadius: '6px' },
  scheduleDays: { display: 'flex', justifyContent: 'space-between' },
  dayButton: { width: '30px', height: '30px', borderRadius: '50%', border: '1px solid #ccc', background: '#f7f7f7', cursor: 'pointer' },
  dayButtonActive: { background: '#0866ff', color: 'white', borderColor: '#0866ff' },
  scheduleTimes: { display: 'flex', alignItems: 'center', gap: '0.5rem' },
  cardWithActions: { backgroundColor: '#f7f7f7', borderRadius: '8px', border: '2px solid transparent', transition: 'all 0.2s', color: '#333', display: 'flex', flexDirection: 'column'},
  cardActions: {
      padding: '0 1rem 1rem 1rem',
      marginTop: 'auto',
      borderTop: '1px solid #eee',
      paddingTop: '1rem',
  },
  cardVariantSelector: {
      display: 'flex',
      gap: '0.5rem',
      marginTop: '1rem',
      paddingTop: '1rem',
      borderTop: '1px solid #eee'
  },
  variantDropdown: {
      flex: 1,
      padding: '0.5rem',
      border: '1px solid #ccc',
      borderRadius: '4px',
      backgroundColor: 'white'
  },
  cardAddButton: {
      padding: '0.5rem 1rem',
      border: 'none',
      borderRadius: '4px',
      backgroundColor: '#2ecc71',
      color: 'white',
      cursor: 'pointer'
  },
  cardAddButtonAdded: {
      padding: '0.5rem 1rem',
      border: 'none',
      borderRadius: '4px',
      backgroundColor: '#27ae60', // A darker green
      color: 'white',
      cursor: 'not-allowed'
  },
  resetButton: {
    background: 'none',
    border: 'none',
    color: '#0866ff',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontSize: '0.9rem',
    padding: '0.5rem',
    marginRight: '1rem'
  },
  listHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 1rem',
    borderBottom: '1px solid #ddd',
    backgroundColor: '#f7f7f7',
  },
  listHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  selectAllCheckbox: {
    marginRight: '0.5rem',
  },
  bulkActionsContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  listFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.75rem 1rem',
    borderTop: '1px solid #ddd',
    backgroundColor: '#f7f7f7',
  },
  filterBarContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '1rem',
    alignItems: 'center',
    padding: '1rem',
    backgroundColor: '#f0f2f5',
    borderRadius: '6px',
    marginBottom: '2rem',
  },
  filterItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    flex: 1,
    minWidth: '150px',
  },
  filterLabel: {
    fontSize: '0.8rem',
    fontWeight: 'bold',
    color: '#606770',
  },
  itemsPerPageContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  itemsPerPageSelect: {
    padding: '0.25rem',
    borderRadius: '4px',
    border: '1px solid #ccc',
  },
  listItemWithCheckbox: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  filterContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem', // This will create the space between the search and filter sections
    marginBottom: '2rem',
  },
  tabContainer: {
    display: 'flex',
    borderBottom: '2px solid #ddd',
    marginBottom: '2rem',
  },
  tabButton: {
    padding: '1rem 1.5rem',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '1.1rem',
    color: '#606770',
    borderBottom: '3px solid transparent',
    marginBottom: '-2px' // Align with the container's bottom border
  },
  tabButtonActive: {
    color: '#0866ff',
    borderBottom: '3px solid #0866ff',
    fontWeight: 'bold'
  },
  multiSelectContainer: {
    maxHeight: '200px',
    overflowY: 'auto',
    border: '1px solid #ccc',
    borderRadius: '6px',
    padding: '0.5rem',
  },
  multiSelectItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.5rem',
  }
};